version: "3.5"
services:
    api:
        build: .
        hostname: api
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    mongo-seed:
        build: ./mongo-seed
        links:
            - mongo
